# Generated by Django 3.2.6 on 2022-06-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regional_women', '0003_super_lady'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_lady',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
    ]
