# Generated by Django 3.2.6 on 2022-06-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regional_women', '0005_alter_course_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='image',
            new_name='video_url',
        ),
    ]
